---

- name: find pip binary
  shell: |
    set -eo pipefail
    whereis -b pip | cut -d " " -f 2
  args:
    executable: /bin/bash
  register: pip_binary
  changed_when: pip_binary.stdout | length > 0

- name: pip upgrade
  command: "{{ pip_binary.stdout }} install --upgrade pip"
  register: pip_upgrade
  changed_when: pip_upgrade.rc != 0

- name: find pip binary
  shell: |
    set -eo pipefail
    whereis -b pip | cut -d " " -f 2
  args:
    executable: /bin/bash
  register: pip_binary
  changed_when: pip_binary.stdout | length > 0

- name: "install python modules with pip"
  include_tasks: install-pip-module.yml
  vars:
    pip_binary_path: "{{ pip_binary.stdout }}"
  loop: "{{ m7s_k8s_base_python_modules }}"
  loop_control:
    loop_var: python_module
