---

- name: change PATH environment
  template:
    src: "{{ role_path + '/template/kube_env.sh.j2' }}"
    dest: "/etc/profile.d/kube_env.sh"
    mode: '0544'

- include_tasks: redhat-repos-x86_64.yml
  when:
    - ansible_facts['architecture'] == 'x86_64'
    - ansible_facts['os_family'] == 'RedHat'

- include_tasks: redhat-packages-x86_64.yml
  when:
    - ansible_facts['architecture'] == 'x86_64'
    - ansible_facts['os_family'] == 'RedHat'

- include_tasks: install-pip-modules.yml
