---

- name: change PATH environment
  template:
    src: "{{ role_path + '/templates/kube_env.sh.j2' }}"
    dest: "/etc/profile.d/kube_env.sh"
    mode: '0544'

- include_tasks: redhat-repos-x86_64.yml
  when:
    - ansible_facts['architecture'] == 'x86_64'
    - ansible_facts['os_family'] == 'RedHat'

- name: install packages
  include_tasks: install-package.yml
  loop: "{{ m7s_k8s_base_install_packages }}"
  loop_control:
    loop_var: package


- include_tasks: install-pip-modules.yml
