---

- name: change PATH environment
  template:
    src: "{{ role_path + '/templates/kube_env.sh.j2' }}"
    dest: "/etc/profile.d/kube_env.sh"
    mode: '0544'

- include_tasks: redhat-repos.yml
  when:
    - ansible_facts['os_family'] == 'RedHat'

- include_tasks: update-cache.yml

- name: install packages
  include_tasks: install-package.yml
  loop: "{{ m7s_k8s_base_install_packages }}"
  loop_control:
    loop_var: package


- include_tasks: install-pip-modules.yml
